=== amayas4456/Projet_Cabinet_Infirmier/XSD/cabinet.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.univ-grenoble-alpes.fr/l3miage/medical"
           xmlns="http://www.univ-grenoble-alpes.fr/l3miage/medical"
           elementFormDefault="qualified">


    <!-- Elément racine -->
    <xs:element name="Cabinet" type="Cabinet"/>

    <!-- Type Complexe pour Cabinet -->
    <xs:complexType name="Cabinet">
        <xs:sequence>
            <xs:element name="nom" type="xs:string"/>
            <xs:element name="adresse" type="Adresse"/>
            <xs:element name="infirmiers" type="Infirmiers" />
            <xs:element name="patients" type="Patients"/>
        </xs:sequence>
    </xs:complexType>


    <!-- Type Complexe pour Adresse -->
    <xs:complexType name="Adresse">
        <xs:sequence>
            <xs:element name="etage" type="xs:int" minOccurs="0"/>
            <xs:element name="numero" type="xs:int" minOccurs="0"/>
            <xs:element name="rue" type="xs:string"/>
            <xs:element name="ville" type="xs:string"/>
            <xs:element name="codePostal">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:pattern value="\d{5}"/> <!-- Code postal à 5 chiffres -->
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- Liste des Infirmiers -->
    <xs:complexType name="Infirmiers">
        <xs:sequence>
            <xs:element name="infirmier" type="Infirmier" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>



    <!-- Type Complexe pour Infirmier -->
    <xs:complexType name="Infirmier">

        <xs:sequence>
            <xs:element name="nom" type="xs:string"/>
            <xs:element name="prenom" type="xs:string"/>
            <xs:element name="photo" type="Photo" />
        </xs:sequence>
        <!-- Attribut pour l'identifiant unique de l'infirmier -->
        <xs:attribute name="id" type="xs:int" use="required"/>

    </xs:complexType>


    <!-- Liste des Patients -->
    <xs:complexType name="Patients">
        <xs:sequence>
            <xs:element name="patient" type="Patient" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Type Complexe pour Patient -->
    <xs:complexType name="Patient">
        <xs:sequence>
            <xs:element name="nom" type="xs:string"/>
            <xs:element name="prenom" type="xs:string"/>
            <xs:element name="sexe" type="Sexe"/>
            <xs:element name="naissance" type="xs:date"/>
            <xs:element name="numero" type="NumeroSS"/>  <!-- Restriction pour NSS en bas -->
            <xs:element name="adresse" type="Adresse"/>
            <xs:element name="visites" type="Visites" maxOccurs="unbounded"/> <!-- un patinet peut avoir plusieurs visites -->
        </xs:sequence>
    </xs:complexType>

    <!-- Type Complexe pour Visites -->

    <xs:complexType name="Visites">
        <xs:sequence>
            <xs:element name="Visite" type="Visite" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>


    <!-- Type Complexe pour Visite -->
    <xs:complexType name="Visite">
        <xs:sequence>
            <xs:element name="date" type="xs:date"/>
            <xs:element name="intervenant" type="xs:int" minOccurs="0"/>
            <xs:element name="actes" type="Actes" minOccurs="0" maxOccurs="unbounded"/> <!-- une visite peut avoir plusieurs actes -->
        </xs:sequence>
    </xs:complexType>

    <!-- Type Complexe pour Acte -->

    <xs:complexType name="Actes">
        <xs:sequence>
            <xs:element name="acte" type="Acte" maxOccurs="unbounded"/> <!-- Plusieurs actes possibles -->
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Acte">
        <xs:simpleContent>
            <xs:extension base="xs:string"> <!-- Texte libre pour description -->
                <xs:attribute name="id" type="xs:string" use="required"/> <!-- Attributs -->
                <xs:attribute name="type" type="TypeSoin" use="required"/>
                <xs:attribute name="cle" type="CleType" use="required"/>
                <xs:attribute name="coef" type="xs:decimal"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>



    <!-- Enumération pour Sexe -->
    <xs:simpleType name="Sexe">
        <xs:restriction base="xs:string">
            <xs:enumeration value="M"/>
            <xs:enumeration value="F"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Enumération pour TypeSoin -->
    <xs:simpleType name="TypeSoin">
        <xs:restriction base="xs:string">
            <xs:enumeration value="pi"/> <!-- Prélèvements et Injections -->
            <xs:enumeration value="pc"/> <!-- Pansements Courants -->
            <xs:enumeration value="pl"/> <!-- Pansements Lourds -->
            <xs:enumeration value="sd"/> <!-- Soins à Domicile -->
        </xs:restriction>
    </xs:simpleType>

    <!-- Enumération pour Clé NGAP -->
    <xs:simpleType name="CleType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="AMI"/> <!-- Acte Médico-Infirmier -->
            <xs:enumeration value="AIS"/> <!-- Acte de Soins Infirmiers -->
            <xs:enumeration value="DI"/>  <!-- Démarche de Soins Infirmiers -->
        </xs:restriction>
    </xs:simpleType>

    <!-- Type restreint pour Numéro de Sécurité Sociale -->
    <xs:simpleType name="NumeroSS">
        <xs:restriction base="xs:string">
            <!-- 1 ou 2 pour le sexe, 2 pour l'année de naissance, 2 pour le mois de naissance, 3 pour le département de naissance, 3 pour le numéro d'ordre, 2 pour la clé -->
            <xs:pattern value="[1-2]\d{2}[0-9]{2}[0-9]{2}[0-9]{3}[0-9]{3}[0-9]{2}"/>
            <!-- 13 chiffres significatifs + 2 chiffres de clé -->
            <xs:length value="15"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Déclaration du type simple "Photo" avec une contrainte de motif -->
    <xs:simpleType name="Photo">
        <xs:restriction base="xs:string">
            <xs:pattern value=".*\.(png|jpg)"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="types">
        <xs:sequence>
            <xs:element name="type" type="TypeSoin" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== amayas4456/Projet_Cabinet_Infirmier/XML/cabinet.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../XSLT/infermier.xsl"?>
<Cabinet xmlns="http://www.univ-grenoble-alpes.fr/l3miage/medical"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.univ-grenoble-alpes.fr/l3miage/medical ../XSD/cabinet.xsd">
    
    
  <!-- Informations du Cabinet -->
      <nom>Cabinet Soins à Grenoble</nom>
      <adresse>
        <etage>1</etage>
        <numero>45</numero>
        <rue>Rue de la Santé</rue>
        <ville>Grenoble</ville>
        <codePostal>38000</codePostal>
      </adresse>

    <!-- Liste des Infirmiers -->
    <infirmiers>
                <infirmier id="001">
                  <nom>Fréchie</nom>
                  <prenom>Sarah</prenom>
                  <photo>sarah.png</photo>
                </infirmier>
      
                <infirmier id="002">
                  <nom>Sidcé</nom>
                  <prenom>Sophie</prenom>
                  <photo>sophie.jpg</photo>
                </infirmier>
      
                <infirmier id="003">
                  <nom>Ochou</nom>
                  <prenom>Paul</prenom>
                  <photo>paul.png</photo>
                </infirmier>
    </infirmiers>

  <!-- Liste des Patients -->
  <patients>
            <patient>
              <nom>Orouge</nom>
              <prenom>Elvire</prenom>
              <sexe>F</sexe>
              <naissance>1982-03-08</naissance>
              <numero>282030837001234</numero>
              <adresse>
                      <rue>Rond-Point de la Croix de Vie</rue>
                      <ville>La Tronche</ville>
                      <codePostal>38700</codePostal>
              </adresse>
                      <visites>
                        <Visite>
                          <date>2015-12-08</date>
                          <intervenant>001</intervenant>
                          <actes>
                            <acte id="201" type="pc" cle="AMI" coef="2.5">
                              Pansement de brûlure étendue
                            </acte>
                          </actes>
                        </Visite>
                      </visites>
            </patient>

            <patient>
            <nom>Pien</nom>
            <prenom>Oscare</prenom>
            <sexe>M</sexe>
            <naissance>1975-03-25</naissance>
            <numero>175032538001234</numero>
            <adresse>
              <rue>Rue Casimir Brenier</rue>
              <ville>Grenoble</ville>
              <codePostal>38000</codePostal>
            </adresse>
                        <visites>
                              <Visite>
                                <date>2015-12-08</date>
                                <intervenant>002</intervenant>
                                <actes>
                                          <acte id="202" type="pi" cle="AMI" coef="1.5">
                                            Ponction veineuse directe
                                          </acte>
                                          <acte id="203" type="pi" cle="AMI" coef="3.0">
                                            Injection intraveineuse d'antalgiques
                                          </acte>
                                </actes>
                              </Visite>
                        </visites>
              </patient>

              <patient>
                
                      <nom>Kapoëtla</nom>
                      <prenom>Xavier</prenom>
                      <sexe>M</sexe>
                      <naissance>2011-08-02</naissance>
                      <numero>111080237001234</numero>
                      <adresse>
                          <numero> 25 </numero>
                        <rue>Rue des Martyrs</rue>
                        <ville>Grenoble</ville>
                        <codePostal>38042</codePostal>
                      </adresse>
                          <visites>
                                    <Visite>
                                      <date>2015-12-08</date>
                                      <intervenant>003</intervenant>
                                            <actes>
                                                      <acte id="204" type="pi" cle="AMI" coef="4.0">
                                                        Injection de plusieurs allergènes pour désensibilisation
                                                      </acte>
                                            </actes>
                                    </Visite>
                          </visites>
                
              </patient>

              <patient>
                        <nom>Alécole</nom>
                        <prenom>Yvon</prenom>
                        <sexe>M</sexe>
                        <naissance>1998-08-22</naissance>
                        <numero>198082205545852</numero>
                        <adresse>
                                  <etage>6</etage>
                                  <numero>50</numero>
                                  <rue>avenue Félix Viallet</rue>
                                  <ville>Grenoble</ville>
                                  <codePostal>38031</codePostal>
                        </adresse>
                        <visites>
                                  <Visite>
                                    <date>2015-12-08</date>
                                    <intervenant>001</intervenant>
                                            <actes>
                                                    <acte id="109" type="pi" cle="AMI" coef="1.0">
                                                            Injection sous-cutanée.
                                                    </acte>
                                            </actes>
                                  </Visite>
                        </visites>
              </patient>


  </patients>
  
  
  
</Cabinet>
